import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Produto from '#models/produto'
import type { TipoProduto } from '#models/produto'

export default class extends BaseSeeder {
  async run() {
    // Limpar tabela antes de inserir
    await Produto.query().delete()

    const produtos = [
      // SERVIÇOS - CONSULTAS
      {
        nome: 'Consulta Medicina Funcional',
        descricao: 'Consulta completa de medicina funcional com avaliação integral do paciente',
        tipo: 'servico' as TipoProduto,
        categoria: 'consulta',
        precoVenda: 350.00,
        precoCusto: null,
        precoParceiro: 280.00,
        duracaoMinutos: 90,
        estoqueAtual: null,
        estoqueMinimo: null,
        controlaEstoque: false,
        parceiroId: 1, // Dr. João Silva Santos
        disponivelAgendamento: true,
        requerPreparo: true,
        instrucoesPreparo: 'Jejum de 12 horas. Trazer exames recentes.',
        tags: ['medicina funcional', 'consulta', 'avaliação integral'],
        codigoInterno: 'CONS-MF-001',
        observacoes: 'Primeira consulta incluiu anamnese completa',
        ativo: true,
      },
      {
        nome: 'Consulta Acupuntura',
        descricao: 'Sessão de acupuntura para tratamento de dores e equilibrio energético',
        tipo: 'servico' as TipoProduto,
        categoria: 'acupuntura',
        precoVenda: 180.00,
        precoCusto: null,
        precoParceiro: 144.00,
        duracaoMinutos: 60,
        estoqueAtual: null,
        estoqueMinimo: null,
        controlaEstoque: false,
        parceiroId: 2, // Dra. Maria Fernanda Costa
        disponivelAgendamento: true,
        requerPreparo: false,
        instrucoesPreparo: null,
        tags: ['acupuntura', 'dor', 'equilibrio'],
        codigoInterno: 'CONS-ACU-001',
        observacoes: 'Agulhas descartáveis incluídas',
        ativo: true,
      },
      {
        nome: 'Consulta Psicológica',
        descricao: 'Sessão de psicoterapia individual',
        tipo: 'servico' as TipoProduto,
        categoria: 'psicologia',
        precoVenda: 200.00,
        precoCusto: null,
        precoParceiro: 160.00,
        duracaoMinutos: 50,
        estoqueAtual: null,
        estoqueMinimo: null,
        controlaEstoque: false,
        parceiroId: 3, // Ana Paula Ribeiro
        disponivelAgendamento: true,
        requerPreparo: false,
        instrucoesPreparo: null,
        tags: ['psicologia', 'terapia', 'individual'],
        codigoInterno: 'CONS-PSI-001',
        observacoes: 'Ambiente reservado e confidencial',
        ativo: true,
      },
      {
        nome: 'Consulta Nutricional',
        descricao: 'Avaliação nutricional completa com plano alimentar personalizado',
        tipo: 'servico' as TipoProduto,
        categoria: 'nutricao',
        precoVenda: 220.00,
        precoCusto: null,
        precoParceiro: 176.00,
        duracaoMinutos: 60,
        estoqueAtual: null,
        estoqueMinimo: null,
        controlaEstoque: false,
        parceiroId: 5, // Dra. Luciana Oliveira
        disponivelAgendamento: true,
        requerPreparo: true,
        instrucoesPreparo: 'Trazer exames de sangue recentes e diário alimentar dos últimos 3 dias',
        tags: ['nutricao', 'dieta', 'emagrecimento'],
        codigoInterno: 'CONS-NUT-001',
        observacoes: 'Inclui bioimpedância',
        ativo: true,
      },

      // SERVIÇOS - PROCEDIMENTOS
      {
        nome: 'Massagem Relaxante',
        descricao: 'Massagem corporal completa para relaxamento e alívio de tensões',
        tipo: 'servico' as TipoProduto,
        categoria: 'massagem',
        precoVenda: 120.00,
        precoCusto: 15.00, // custo dos óleos
        precoParceiro: 84.00,
        duracaoMinutos: 60,
        estoqueAtual: null,
        estoqueMinimo: null,
        controlaEstoque: false,
        parceiroId: 4, // Carlos Eduardo Mendes
        disponivelAgendamento: true,
        requerPreparo: false,
        instrucoesPreparo: null,
        tags: ['massagem', 'relaxamento', 'bem-estar'],
        codigoInterno: 'PROC-MAS-001',
        observacoes: 'Óleos essenciais incluídos',
        ativo: true,
      },
      {
        nome: 'Drenagem Linfática',
        descricao: 'Drenagem linfática manual para redução de edemas e melhora circulatória',
        tipo: 'servico' as TipoProduto,
        categoria: 'massagem',
        precoVenda: 140.00,
        precoCusto: 10.00,
        precoParceiro: 98.00,
        duracaoMinutos: 50,
        estoqueAtual: null,
        estoqueMinimo: null,
        controlaEstoque: false,
        parceiroId: 4, // Carlos Eduardo Mendes
        disponivelAgendamento: true,
        requerPreparo: false,
        instrucoesPreparo: null,
        tags: ['drenagem', 'linfática', 'circulação'],
        codigoInterno: 'PROC-DRE-001',
        observacoes: 'Indicado pós-cirúrgico',
        ativo: true,
      },
      {
        nome: 'Limpeza de Pele Profunda',
        descricao: 'Limpeza de pele profunda com extração e hidratação',
        tipo: 'servico' as TipoProduto,
        categoria: 'estetica',
        precoVenda: 180.00,
        precoCusto: 25.00,
        precoParceiro: 126.00,
        duracaoMinutos: 90,
        estoqueAtual: null,
        estoqueMinimo: null,
        controlaEstoque: false,
        parceiroId: 6, // Roberto Silva Ferreira
        disponivelAgendamento: true,
        requerPreparo: true,
        instrucoesPreparo: 'Não usar ácidos na pele 3 dias antes do procedimento',
        tags: ['estetica', 'limpeza', 'pele'],
        codigoInterno: 'PROC-LIM-001',
        observacoes: 'Produtos dermocosméticos incluídos',
        ativo: true,
      },

      // PRODUTOS - SUPLEMENTOS
      {
        nome: 'Vitamina D3 2000UI',
        descricao: 'Suplemento de Vitamina D3 para fortalecimento ósseo e imunológico',
        tipo: 'produto' as TipoProduto,
        categoria: 'suplemento',
        precoVenda: 45.00,
        precoCusto: 28.00,
        precoParceiro: null,
        duracaoMinutos: null,
        estoqueAtual: 50,
        estoqueMinimo: 10,
        controlaEstoque: true,
        parceiroId: null,
        disponivelAgendamento: false,
        requerPreparo: false,
        instrucoesPreparo: null,
        tags: ['vitamina', 'suplemento', 'imunidade'],
        codigoInterno: 'PROD-VIT-001',
        observacoes: 'Frasco com 60 cápsulas',
        ativo: true,
      },
      {
        nome: 'Ômega 3 Premium',
        descricao: 'Suplemento de Ômega 3 concentrado para saúde cardiovascular',
        tipo: 'produto' as TipoProduto,
        categoria: 'suplemento',
        precoVenda: 89.00,
        precoCusto: 55.00,
        precoParceiro: null,
        duracaoMinutos: null,
        estoqueAtual: 30,
        estoqueMinimo: 5,
        controlaEstoque: true,
        parceiroId: null,
        disponivelAgendamento: false,
        requerPreparo: false,
        instrucoesPreparo: null,
        tags: ['omega3', 'cardiovascular', 'anti-inflamatório'],
        codigoInterno: 'PROD-OME-001',
        observacoes: 'Cápsulas de 1000mg - Frasco com 120 unidades',
        ativo: true,
      },

      // PRODUTOS - COSMÉTICOS
      {
        nome: 'Protetor Solar Facial FPS 60',
        descricao: 'Protetor solar facial com proteção UVA/UVB, textura fluida',
        tipo: 'produto' as TipoProduto,
        categoria: 'cosmetico',
        precoVenda: 65.00,
        precoCusto: 38.00,
        precoParceiro: null,
        duracaoMinutos: null,
        estoqueAtual: 25,
        estoqueMinimo: 8,
        controlaEstoque: true,
        parceiroId: null,
        disponivelAgendamento: false,
        requerPreparo: false,
        instrucoesPreparo: null,
        tags: ['protetor solar', 'facial', 'fps60'],
        codigoInterno: 'PROD-PRO-001',
        observacoes: 'Tubo de 50ml - Base fluida',
        ativo: true,
      },
      {
        nome: 'Sérum Vitamina C 20%',
        descricao: 'Sérum facial antioxidante com 20% de Vitamina C para rejuvenescimento',
        tipo: 'produto' as TipoProduto,
        categoria: 'cosmetico',
        precoVenda: 120.00,
        precoCusto: 72.00,
        precoParceiro: null,
        duracaoMinutos: null,
        estoqueAtual: 15,
        estoqueMinimo: 3,
        controlaEstoque: true,
        parceiroId: null,
        disponivelAgendamento: false,
        requerPreparo: false,
        instrucoesPreparo: null,
        tags: ['vitamina c', 'antioxidante', 'rejuvenescimento'],
        codigoInterno: 'PROD-SER-001',
        observacoes: 'Frasco de 30ml com pump - Manter refrigerado',
        ativo: true,
      },

      // PRODUTOS - EQUIPAMENTOS
      {
        nome: 'Dermaroller 0.5mm',
        descricao: 'Dermaroller para estimulação da produção de colágeno',
        tipo: 'produto' as TipoProduto,
        categoria: 'equipamento',
        precoVenda: 85.00,
        precoCusto: 45.00,
        precoParceiro: null,
        duracaoMinutos: null,
        estoqueAtual: 8,
        estoqueMinimo: 2,
        controlaEstoque: true,
        parceiroId: null,
        disponivelAgendamento: false,
        requerPreparo: false,
        instrucoesPreparo: null,
        tags: ['dermaroller', 'colágeno', 'microagulhamento'],
        codigoInterno: 'PROD-DER-001',
        observacoes: 'Uso individual - Esterilizado',
        ativo: true,
      }
    ]

    // Inserir produtos
    for (const produtoData of produtos) {
      await Produto.create(produtoData)
    }

    console.log('✅ Seeder de produtos executado com sucesso!')
    console.log(`📦 ${produtos.length} produtos/serviços criados`)
    console.log('🔹 Serviços: Consultas, Massagens, Procedimentos Estéticos')
    console.log('🔹 Produtos: Suplementos, Cosméticos, Equipamentos')
  }
}